CREATE DATABASE MEDICALGROUP_JULIA;
GO

USE MEDICALGROUP_JULIA;
GO

CREATE TABLE TIPOUSUARIO(
  idTipoUsuario TINYINT PRIMARY KEY IDENTITY,
  tituloTipoUsuario VARCHAR(100) NOT NULL UNIQUE
);
GO

CREATE TABLE USUARIO(
  idUsuario SMALLINT PRIMARY KEY IDENTITY,
  idTipoUsuario TINYINT FOREIGN KEY REFERENCES tipoUsuario(idTipoUsuario),
  nomeUsuario VARCHAR(50) NOT NULL,
  emailUsuario VARCHAR(256) NOT NULL UNIQUE,
  senhaUsuario VARCHAR(15) NOT NULL
);
GO

CREATE TABLE CLINICA(
  idClinica SMALLINT PRIMARY KEY IDENTITY,
  nomeClinica VARCHAR(100) NOT NULL,
  endereco VARCHAR(200) NOT NULL UNIQUE,
  cnpj VARCHAR(20) NOT NULL UNIQUE,
  razaoSocial VARCHAR(200) NOT NULL UNIQUE
);
GO


CREATE TABLE ESPECIALIDADE(
  idEspecialidade TINYINT PRIMARY KEY IDENTITY,
  descricaoEspecialidade VARCHAR(100) NOT NULL UNIQUE
);
GO


CREATE TABLE SITUACAO(
  idSituacao TINYINT PRIMARY KEY IDENTITY,
  descricaoSituacao VARCHAR(100) UNIQUE NOT NULL
);
GO


CREATE TABLE PACIENTE(
  idPaciente INT PRIMARY KEY IDENTITY,
  idUsuario SMALLINT FOREIGN KEY REFERENCES usuario(idUsuario),
  nomePaciente VARCHAR(100) NOT NULL,
  dataNascimento DATETIME NOT NULL,
  cpf VARCHAR(15) NOT NULL UNIQUE,
  enderecoPaciente VARCHAR(200) UNIQUE NOT NULL
);
GO

ALTER TABLE PACIENTE
ADD idUsuario SMALLINT FOREIGN KEY REFERENCES usuario(idUsuario)


CREATE TABLE MEDICO(
  idMedico SMALLINT PRIMARY KEY IDENTITY,
  idUsuario SMALLINT FOREIGN KEY REFERENCES usuario(idUsuario),
  idClinica SMALLINT FOREIGN KEY REFERENCES CLINICA(idClinica),
  idEspecialidade TINYINT FOREIGN KEY REFERENCES ESPECIALIDADE(idEspecialidade),
  nomeMedico VARCHAR(100),
  crm VARCHAR(20) NOT NULL UNIQUE
);
GO

ALTER TABLE MEDICO
ADD idUsuario SMALLINT FOREIGN KEY REFERENCES usuario(idUsuario)

CREATE TABLE CONSULTA(
  idConsulta INT PRIMARY KEY IDENTITY,
  idSituacao TINYINT FOREIGN KEY REFERENCES situacao(idSituacao) DEFAULT(1),
  idPaciente INT FOREIGN KEY REFERENCES paciente(idPaciente),
  idMedico SMALLINT FOREIGN KEY REFERENCES medico(idMedico),
  dataConsulta DATETIME NOT NULL
);
GO

